name: Update README with Challenge Count

on:
  push:
    paths:
      - 'python/**.py'
      - 'sql/**.sql'
  workflow_dispatch:

jobs:
  count-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Count .py and .sql files
        id: count
        run: |
          PY_COUNT=$(find python -name "*.py" | wc -l)
          SQL_COUNT=$(find sql -name "*.sql" | wc -l)
          TOTAL_COUNT=$((PY_COUNT + SQL_COUNT))
          echo "Total challenges: $TOTAL_COUNT"
          echo "total=$TOTAL_COUNT" >> $GITHUB_OUTPUT

      - name: Update README.md badge
        run: |
          TOTAL=${{ steps.count.outputs.total }}
          sed -i 's/\(Total_Desafios_Resolvidos-\)[0-9]\+/\\1'"$TOTAL"'/g' README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update README challenge count"
          file_pattern: README.md
